config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'calendars/index'
  # get 'calendars/show'
  get 'events/index'
  # devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :calendars, only: %i[index show]

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
# frozen_string_literal: true

class Calendar < ApplicationRecord
  extend GoogleCalendarApi
  validates :name, presence: true
  'hl'
  validates :google_id, presence: true
  has_many :events, dependent: :destroy
  belongs_to :user

  def self.sync_cal(user)
    cals = get_cals user

    cals.each do |i|
      calendar = Calendar.find_or_initialize_by(google_id: i[:google_id], user_id: user.id)
      calendar.assign_attributes(i)
      calendar.save
    end

    client = get_google_calendar_client user
    user.calendars.each do |i|
      events = client.list_events(i.google_id).items
      events.each do |e|
        event = Event.find_or_initialize_by(google_id: e.id, calendar_id: i.id)
        event.assign_attributes({ title: e.summary, description: e.description,
                                  start_date: e.start.date_time || e.start.date,
                                  end_date: e.end.date_time || e.end.date })
        event.save
      end
    end
  end
end

app/models/concerns/google_calendar_api.rb
# frozen_string_literal: true

require 'google/apis/calendar_v3'
require 'google/api_client/client_secrets.rb'

module GoogleCalendarApi
  include ActiveSupport::Concern

  def get_google_calendar_client(current_user)
    client = Google::Apis::CalendarV3::CalendarService.new
    unless current_user.present? &&
           current_user.access_token.present? &&
           current_user.refresh_token.present?
      return
    end

    secrets = Google::APIClient::ClientSecrets.new({
                                                     'web' => {
                                                       'access_token' => current_user
                                                       .access_token,
                                                       'refresh_token' => current_user
                                                       .refresh_token,
                                                       'client_id' => Rails.application.credentials
                                                       .google[:client_id],
                                                       'client_secret' => Rails.application
                                                       .credentials
                                                       .google[:client_secret]
                                                     }
                                                   })
    begin
      client.authorization = secrets.to_authorization
      client.authorization.grant_type = 'refresh_token'

      if current_user.expired?
        client.authorization.refresh!
        current_user.update_attributes(
          access_token: client.authorization.access_token,
          refresh_token: client.authorization.refresh_token,
          expires_at: client.authorization.expires_at.to_i
        )
      end
    rescue StandardError => e
      raise e.message
    end
    client
  end

  def sync_events(user)
    client = get_google_calendar_client(user)
    calendars = client.list_calendar_lists.items
  end

  def get_cals(user)
    client = get_google_calendar_client(user)
    calendars = client.list_calendar_lists.items.map do |i|
      { name: i.summary, bg_color: i.background_color, google_id: i.id }
    end
  end
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates :title, presence: true
  validates :google_id, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: [:google_oauth2]

  has_many :calendars, dependent: :destroy
  has_many :events, through: :calendars

  def self.from_omniauth(auth)
    user = User.where(provider: auth.try(:provider) || auth['provider'],
                      uid: auth.try(:uid) || auth['uid']).first
    if user
      user
    else
      registered_user = User.where(provider: auth.try(:provider) || auth['provider'],
                                   uid: auth.try(:uid) || auth['uid']).first ||
                        User.where(email: auth.try(:info).try(:email) || auth['info']['email'])
                            .first
      if registered_user
        unless registered_user.provider == (auth.try(:provider) || auth['provider']) &&
               registered_user.uid == (auth.try(:uid) || auth['provider'])
          registered_user.update_attributes(provider: auth.try(:provider) || auth['provider'],
                                            uid: auth.try(:uid) || auth['uid'])
        end
        return registered_user
      else
        user = User.new(provider: auth.try(:provider) || auth['provider'],
                        uid: auth.try(:uid) || auth['uid'])
        user.email = auth.try(:info).try(:email) || auth['info']['email']
        user.password = Devise.friendly_token[0, 20]
        user.first_name = auth.info.name.split(' ')[0]
        user.last_name = auth.info.name.split(' ')[1]
        user.access_token = auth.credentials.token
        user.expires_at = auth.credentials.expires_at
        user.refresh_token = auth.credentials.refresh_token
        user.save
        puts user
      end
      user
    end
  end

  def expired?
    expires_at < Time.current.to_i
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/calendars_controller.rb
# frozen_string_literal: true

class CalendarsController < ApplicationController
  def index
    if current_user.calendars.empty? || params[:sync] == 'true'
      calenders = Calendar.sync_cal current_user
      @cals = current_user.calendars
    else
      @cals = current_user.calendars
    end
  end

  def show
    @calendar = Calendar.find(params[:id])
    if params[:older] == 'true'
      @events = @calendar.events.where('start_date <= ?', Date.today)
                         .order(start_date: :desc)
    else
      @events = @calendar.events.where('start_date >= ?', Date.today)
                         .order(:start_date)
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < ApplicationController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      auth = request.env['omniauth.auth']
      @user.access_token = auth.credentials.token
      @user.expires_at = auth.credentials.expires_at
      @user.refresh_token = auth.credentials.refresh_token
      @user.save!
      sign_in(@user)
      redirect_to calendars_path
    else
      puts @user.errors.to_a
      puts request.env['omniauth.auth']
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/calendars_helper.rb
# frozen_string_literal: true

module CalendarsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
# frozen_string_literal: true

module Users::OmniauthCallbacksHelper
end

app/views/calendars/index.html.erb
<h1>My Calendars listing</h1>

<p>Select any calendar to list the events</p>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cals.each do |cal| %>
    <tr>
        <td><%= link_to cal.name, calendar_path(cal) %></td>
    </tr>  
    <% end %>
  </tbody>
</table>

app/views/calendars/show.html.erb
<%if params[:older] == 'true'%>
 <h1>Older Events listing</h1>
<%else%>
 <h1>Future Events listing</h1>
<%end%>
<% if @events.empty? %>
<p>No Events to display <%=link_to "View Older Events", calendar_path(@calendar, older: true) %></p>
<%else %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Time</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
    <tr>
        <td><%= event.title %></td>
        <td><%="From #{event.start_date.strftime('%m/%d/%y at %I:%M%p')} to #{event.end_date.strftime('%m/%d/%y at %I:%M%p')}"%></td>
    </tr>  
    <% end %>
  </tbody>
</table>
<%end%>

app/views/home/index.html.erb
<div class="jumbotron">
	<h1>Vivid Calendar</h1>
  <% if user_signed_in? %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger rounded-0" %>
  <% else %>
      <%= link_to "Sign in with Google to see the calandar", user_google_oauth2_omniauth_authorize_path, class: "btn btn-danger" %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VividCalendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          
             <%= yield %>
         
          <div class="row">
            <div class="col-xs-6 col-lg-4">
            </div><!--/.col-xs-6.col-lg-4-->
          </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->
        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
          <div class="list-group">
            <% if !user_signed_in? %>
              <%= link_to "Sign in", user_google_oauth2_omniauth_authorize_path, class: "list-group-item" %>
            <% else %>
             <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "list-group-item" %>
              <%= link_to "Sync My Calendar", calendars_path(sync: true), class: "list-group-item" %>
            <% end %>
          </div>
        </div><!--/.sidebar-offcanvas-->
      </div>
      
      <hr>
      
  </body>
</html>